### ISSUE TITLE
Closed windows not removed from context menu

### ISSUE THREAD

**Issue by iwconfig** [l10nelw/winger#6] opened 2021-12-29 21:28 UTC
Hello!

I had a lot of windows opened a while back, and then closed each window as I went through each tab. When I only had **three windows left**, I did a right click on a pinned tab and accidentally noticed the list in "Send Tab to Window" is not updated to reflect the current number of opened windows.

I have only tried opening and closing Winger popup but "Send Tab to Window" context menu stays the same.

![bild](https://user-images.githubusercontent.com/10843441/147704411-494a4306-072f-4f36-b2cc-61d9da2ac9dd.png)

**Comment by iwconfig** [comment] 2021-12-30 00:04
The non existing windows are still listed even if there's only one window opened.

This might be unrelated but I also noticed when I open new windows, the new window name does not reflect the _current_ number of already open windows incremented by 1.

![bild](https://user-images.githubusercontent.com/10843441/147711425-9c49a813-703e-4e6f-80f4-601f82a7628c.png)

Is this an intended behavior?

---
OK now I have restarted my web browser and the non existing windows have disappeared. And window number has reset as well.

![bild](https://user-images.githubusercontent.com/10843441/147711685-19d62418-76a4-4c2e-bdb1-c85040a31f12.png)

**Comment by l10nelw** [comment] 2022-11-24 02:40
Hello! I have noticed the buggy Send Tab to Window menu myself and it will be fixed in the next version.

>new window name does not reflect the current number of already open windows incremented by 1.
Yes it's intended behaviour, it's just a simple count of windows opened during the entire current session. Heads up though, this auto default naming will be dropped in the next version to simplify things.

**Comment by iwconfig** [comment] 2022-11-24 13:28
Wonderful! :ok_hand::ok_hand:

**Closed** 2022-12-01 02:51 UTC
